### ISSUE TITLE
System.Exception: 'Unrecognized token at index = 1'

### ISSUE THREAD

**Issue by ilCave** [mgholam/RaptorDB-Document#13]
I receive the error in Title when I try to execute a full text search (ex. Db.FullTextSearch(filter);).
The Db is a singleton property of type RaptorDB.RaptorDB:

<img width="1043" alt="screenshot 2019-01-11 at 00 41 41" src="https://user-images.githubusercontent.com/35065746/51004136-b5dd2900-1539-11e9-80f3-26e18da59b3f.png">

exactly the error occurs when I try to open db. (in the db there are about 1000 objects)

this is the stack trace. 

at fastBinaryJSON.BJsonParser.ParseValue(Boolean& breakparse)
   at fastBinaryJSON.deserializer.ToObject(Byte[] json, Type type)
   at fastBinaryJSON.deserializer.ToObject[T](Byte[] json)
   at fastBinaryJSON.BJSON.ToObject[T](Byte[] json)
   at RaptorDB.StorageFileHF.InitializeFreeList()
   at RaptorDB.StorageFileHF.Initialize(String filename, UInt16 blocksize)
   at RaptorDB.StorageFileHF..ctor(String filename, UInt16 blocksize)
   at RaptorDB.KeyStoreHF..ctor(String folder)
   at RaptorDB.RaptorDB.Initialize()
   at RaptorDB.RaptorDB..ctor(String FolderPath, ITokenizer tokenizer)
   at RaptorDB.RaptorDB.Open(String FolderPath)

**Comment by mgholam** [comment]
Did you upgrade the dlls?

**Comment by deviousasti** [comment]
Same error here.
Every time there is an improper termination of the app, this happens.
(Even if no writes were made to the DB).

**Comment by deviousasti** [comment]
@ilCave Any luck so far?

**Comment by mgholam** [comment]
Should be fixed in `v4.0.7`
